kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: maven:3-jdk-11
    commands:
      - mvn clean package

  - name: sonarqube analysis
    image: sonarsource/sonar-scanner-cli
    environment:
      SONAR_SCANNER_OPTS: "-Dsonar.sources=. -Dsonar.projectKey=easv-devops_HelloJava_AY3Gqs7kEVvRW2O60EGK -Dsonar.host.url=http://sonar.setgo.dk:9000 -Dsonar.token=sqp_f19cf0ce299865e0e40598e6e15bd7ef76082407"
    commands:
      - ls -li
      - sonar-scanner


# steps:
#   - name: build
#     image: maven:3.8.1-jdk-11
#     commands:
#       - mvn clean verify sonar:sonar \
#         -Dsonar.projectKey=easv-devops_HelloJava_AY3Gqs7kEVvRW2O60EGK \
#         -Dsonar.projectName='HelloJava' \
#         -Dsonar.host.url=http://sonar.setgo.dk:9000 \
#         -Dsonar.token=sqp_f19cf0ce299865e0e40598e6e15bd7ef76082407